#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ntp'
cookbook 'chef-client'
cookbook 'apt'
cookbook 'nginx'
cookbook 'git'
cookbook 'java'
cookbook 'rbenv'